#!/usr/bin/env python3
"""Mock STT service for DARIA"""

import os
import time
from flask import Flask, request, jsonify

app = Flask(__name__)

@app.route('/health', methods=['GET'])
def health():
    """Health check endpoint"""
    return jsonify({"status": "ok"})

@app.route('/transcribe', methods=['POST'])
def transcribe():
    """Mock transcribe endpoint"""
    # Return a mock transcript
    return jsonify({
        "status": "success",
        "transcript": "This is a mock transcript generated by the STT service.",
        "confidence": 0.95
    })

if __name__ == "__main__":
    port = int(os.environ.get("PORT", 5016))
    app.run(host='0.0.0.0', port=port)
